### ISSUE TITLE
Logs complaining about missing enviroment values. .env present and manually put values in compose as well

### ISSUE THREAD

**Issue by corbui317** [Pukabyte/alfred#1]
**Describe the bug**

**Environment:**
 - OS: [Ubuntu 20.04]
 - Docker version: [27.5.0]
 - Docker Compose version: [v2.32.4]
 - Alfred version: [0.0.12]

**Additional context**

**Logs**
2025-03-30 21:22:55.176 | ERROR    | __main__:<module>:17 - Required environment variables SYMLINK_DIR and TORRENTS_DIR must be set

``` 

![Image](https://github.com/user-attachments/assets/8e3cc3c2-4dd3-4388-b590-b91ef9a7bf56)

![Image](https://github.com/user-attachments/assets/a66639da-e0c5-44e9-b45e-259fd9c3636a)

**Comment by Pukabyte** [comment]
I'm not able to see the images you've posted.

Is the .env file owned by the same user specified in the compose `user: 1000:1000`

**Comment by naby-dev** [comment]
Hey @Pukabyte  I have the same issue:

![Image](https://github.com/user-attachments/assets/f5a6e7e7-6436-49f7-859c-2f298d3c1d9a)


.env
```
DOCKER_APPDATA=/opt/appdata
PLEX_MEDIA=/mnt/plex
REMOTE_MOUNT=/mnt/remote/realdebrid
```

docker-compose.yml
```
networks:
  mediarr-network:
    external: true

services:
    alfred:
      container_name: alfred
      image: ghcr.io/pukabyte/alfred:latest
      user: "1000:1000"
      environment:
        - TZ={TZ}
      ports:
        - 5000:5000
      networks:
        - mediarr-network
      volumes:
        - ${DOCKER_APPDATA}/alfred:/app/data
        - ${PLEX_MEDIA}:${PLEX_MEDIA}
        - ${REMOTE_MOUNT}:${REMOTE_MOUNT}
      restart: unless-stopped
```
